"""add classifications and enodeb table

Revision ID: 148af5d6d386
Revises: b9df7cd058d7
Create Date: 2019-12-06 11:33:34.659214

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '148af5d6d386'
down_revision = 'b9df7cd058d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tower_data', sa.Column('classification', sa.Enum('unknown', 'legitimate', 'small_cell', 'suspicious', 'CSS', name='towerclassification'), server_default="unknown", nullable=False))
    op.add_column('tower_data', sa.Column('external_db', sa.Enum('not_present', 'unknown', 'wigle', 'opencellid', name='externaltowers'), server_default="unknown", nullable=False))

    op.create_table('enodebs',
    sa.Column('id',  mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('mcc', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('mnc', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('tac', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('enodeb_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('classification', sa.Enum('unknown', 'legitimate', 'small_cell', 'suspicious', 'CSS', name='towerclassification'), server_default="unknown", nullable=False),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tower_data', 'external_db')
    op.drop_column('tower_data', 'classification')
    op.drop_table('enodebs')
    # ### end Alembic commands ###
