"""add frequency and enodeb_id

Revision ID: 6d0126ce7607
Revises:
Create Date: 2019-04-08 14:33:57.150620

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql
import os
from database import init_db, Tower

# revision identifiers, used by Alembic.
revision = '6d0126ce7607'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tower_data', sa.Column('enodeb_id', sa.Integer(), nullable=True))
    op.add_column('tower_data', sa.Column('frequency', sa.Float(), nullable=True))
    op.add_column('tower_data', sa.Column('sector_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###
    sess = init_db(os.environ['CH_PROJ'])
    for t in sess.query(Tower).all():
        t.frequency = t.get_frequency()
        t.sector_id = t.get_sector_id()
        t.enodeb_id = t.get_enodeb_id()
    sess.commit()



def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tower_data', 'sector_id')
    op.drop_column('tower_data', 'frequency')
    op.drop_column('tower_data', 'enodeb_id')
    # ### end Alembic commands ###
